### ISSUE TITLE
Create webspace for project awareness

### ISSUE THREAD

**Issue by grubino** [PlunderKnowledge/nifty-messenger#2]
Forcing people to go to github to find out about the project is a recipe for restricting users to developers.  This is NOT a delicious meal.

**Comment by recursivelycurious** [comment]
@grubino -- some questions:
- Why label an issue `wontfix` and then assign it?
- There is no README.md or other information about the project, no real context. If my assistance is desired, context and clarity would be appreciated.

**Comment by recursivelycurious** [comment]
@grubino -- And, speaking of non delicious experiences, I am unable to re-assign, un-assign or close this issue.
